# Generated by Django 4.1.3 on 2022-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
