# Generated by Django 4.1.3 on 2022-11-30 13:24
import os

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name=os.environ.get('DJ_GROUP_STUDENTS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_INSTRUCTORS'))


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get(name=os.environ.get('DJ_GROUP_STUDENTS')).delete()
    Group.objects.get(name=os.environ.get('DJ_GROUP_INSTRUCTORS')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_account_is_instructor'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
